name: 'markdown-link-check'
description: 'Check if all links are valid in markdown files.'
author: 'Gaurav Nelson'
branding:
  icon: 'link'  
  color: 'green'
inputs:
  use-quiet-mode:
    description: 'Use yes to enable markdown-link-check quiet mode which only list errors.'
    required: true
    default: 'no'
  use-verbose-mode:
    description: 'Use yes to enable markdown-link-check verbose mode which lists additional details.'
    required: true
    default: 'no'
  config-file:
    description: 'Specify path to a markdown-link-check JSON configuration file.'
    required: true
    default: 'mlc_config.json'
  folder-path:
    description: 'Specify path to a custom folder where your markdown files are located.'
    required: true
    default: '.'
  max-depth:
    description: 'Specify a max-depth of directories you want to search for markdown files.'
    required: true
    default: '-1'
  check-modified-files-only:
    description: 'Use yes to only check for modified markdown files instead of checking all markdown files.'
    required: true
    default: 'no'
  base-branch:
    description: 'Use this to specify the base branch against which the action finds the modififed files.'
    required: true
    default: 'master'
  file-extension:
    description: 'Use this to specify the file extension of Markdown files.'
    required: true
    default: '.md'
  file-path:
    description: 'Specify additional files you want to check'
    required: true
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.use-quiet-mode }}
    - ${{ inputs.use-verbose-mode }}
    - ${{ inputs.config-file }}
    - ${{ inputs.folder-path }}
    - ${{ inputs.max-depth }}
    - ${{ inputs.check-modified-files-only }}
    - ${{ inputs.base-branch }}
    - ${{ inputs.file-extension }}
    - ${{ inputs.file-path }}
