name: "markdown-link-check"
description: "Check if all links are valid in markdown files."
author: "Gaurav Nelson"
branding:
  icon: "link"
  color: "green"
inputs:
  use-quiet-mode:
    description: "Use true to enable markdown-link-check quiet mode which only list errors."
    required: false
    default: "false"
  use-verbose-mode:
    description: "Use true to enable markdown-link-check verbose mode which lists additional details."
    required: false
    default: "false"
  config-file:
    description: "Specify path to a markdown-link-check JSON configuration file."
    required: false
    default: "mlc_config.json"
  folder-path:
    description: "Specify path to a custom folder where your markdown files are located."
    required: false
    default: "."
  max-depth:
    description: "Specify a max-depth of directories you want to search for markdown files."
    required: false
    default: "-1"
  check-modified-files-only:
    description: "Use true to only check for modified markdown files instead of checking all markdown files."
    required: false
    default: "false"
  base-branch:
    description: "Use this to specify the base branch against which the action finds the modified files."
    required: false
    default: "master"
  file-extension:
    description: "Use this to specify the file extension of Markdown files."
    required: false
    default: ".md"
  file-path:
    description: "Specify additional files you want to check"
    required: false
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"
  entrypoint: entrypoint.sh
  args:
    - --quiet ${{ inputs.use-quiet-mode || 'false' }}
    - --verbose ${{ inputs.use-verbose-mode || 'false' }}
    - --config ${{ inputs.config-file || 'mlc_config.json' }}
    - --folder ${{ inputs.folder-path || '.' }}
    - --depth ${{ inputs.max-depth || '-1' }}
    - --modified ${{ inputs.check-modified-files-only || 'false' }}
    - --branch ${{ inputs.base-branch || 'master' }}
    - --ext ${{ inputs.file-extension || '.md' }}
    - --path ${{ inputs.file-path || '' }}
